"""
new_shard.py — Create a new WorldWeaver shard directory from template.

Usage:
    python scripts/new_shard.py <city_id> [OPTIONS]

    <city_id>           Slug for the new shard (e.g. portland, tokyo, mission)
    --port PORT         Backend port (default: 8001)
    --type TYPE         Shard type: city | world | neighborhood (default: city)
    --shard-id ID       Federation-wide node ID (default: generated directory name)
    --federation URL    Federation root URL (e.g. http://localhost:9000)
    --token SECRET      Shared secret for federation auth (FEDERATION_TOKEN)
    --base-dir DIR      Parent directory for the shard (default: ..)
    --city-pack-dir DIR Path to a pre-built city pack directory (auto-detected if omitted)
    --dry-run           Print what would be created without writing files

Examples:
    # Create a Portland city shard (auto-detects data/cities/portland/)
    python scripts/new_shard.py portland --port 8001 \\
        --federation http://host.docker.internal:9000 --token my-secret

    # Create a Portland city shard with explicit city pack path
    python scripts/new_shard.py portland --port 8001 \\
        --city-pack-dir /path/to/portland \\
        --federation http://host.docker.internal:9000 --token my-secret

    # Create the world federation root
    python scripts/new_shard.py world --type world --port 9000 --token my-secret

    # Then seed the shard:
    python scripts/seed_world.py --shard-dir ../ww_pdx
"""

from __future__ import annotations

import argparse
import base64
import json
import os
import re
import secrets
import shutil
import sys
from pathlib import Path

ENGINE_ROOT = Path(__file__).resolve().parent.parent
if str(ENGINE_ROOT) not in sys.path:
    sys.path.insert(0, str(ENGINE_ROOT))

from src.services.federation_node_auth import generate_node_identity  # noqa: E402

# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------

_ENV_CITY = """\
COMPOSE_PROJECT_NAME={compose_project_name}
CITY_ID={city_id}
SHARD_ID={shard_id}
BACKEND_PORT={port}
SHARD_TYPE=city
WW_SHARD_EXPERIENCE_PATH={experience_path}
FEDERATION_URL={federation_url}
WW_RUNTIME_FEDERATION_URL={runtime_federation_url}
FEDERATION_TOKEN={token}
WW_NODE_PRIVATE_KEY_PATH=identity/node.key
WW_PUBLIC_URL=http://localhost:{port}
WW_CLIENT_URL=
WW_DB_HOST=db
WW_DB_PORT=5432
WW_DB_EXTERNAL_PORT={db_external_port}
WW_DB_NAME=worldweaver_{city_id}
WW_DB_USER=postgres
WW_DB_PASSWORD=postgres
WW_DATABASE_URL=
WW_CITY_TIMEZONE={city_timezone}
WW_JWT_SECRET={jwt_secret}
WW_DATA_ENCRYPTION_KEY={data_encryption_key}
RESEND_API_KEY=
RESEND_FROM_EMAIL=noreply@worldweaver.example.com
OPENROUTER_API_KEY=
LLM_BASE_URL=https://openrouter.ai/api/v1
LLM_MODEL=google/gemini-3-flash-preview
LLM_CITY_BUILDER_MODEL=google/gemini-3-flash-preview
WW_INFERENCE_KEY=
WW_INFERENCE_URL=https://openrouter.ai/api/v1
WW_INFERENCE_MODEL=google/gemini-3-flash-preview
WW_DOULA=1
WW_DOULA_MODEL=
"""

_ENV_WORLD = """\
COMPOSE_PROJECT_NAME={compose_project_name}
SHARD_ID={shard_id}
BACKEND_PORT={port}
SHARD_TYPE=world
WW_SHARD_EXPERIENCE_PATH=
FEDERATION_TOKEN={token}
WW_NODE_PRIVATE_KEY_PATH=identity/node.key
WW_PUBLIC_URL=http://localhost:{port}
WW_CLIENT_URL=
WW_DB_HOST=db
WW_DB_PORT=5432
WW_DB_EXTERNAL_PORT={db_external_port}
WW_DB_NAME=worldweaver_world
WW_DB_USER=postgres
WW_DB_PASSWORD=postgres
WW_DATABASE_URL=
WW_JWT_SECRET={jwt_secret}
WW_DATA_ENCRYPTION_KEY={data_encryption_key}
RESEND_API_KEY=
RESEND_FROM_EMAIL=noreply@worldweaver.example.com
OPENROUTER_API_KEY=
LLM_BASE_URL=https://openrouter.ai/api/v1
LLM_MODEL=google/gemini-3-flash-preview
LLM_CITY_BUILDER_MODEL=google/gemini-3-flash-preview
"""

_COMPOSE_CITY = """\
# WorldWeaver shard: {city_id}
# Generated by scripts/new_shard.py
# Resident workspaces are currently co-located here for development. The mount is temporary hosting,
# not part of resident identity or ownership.

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: ${{WW_DB_NAME:-worldweaver_{city_id}}}
      POSTGRES_USER: ${{WW_DB_USER:-postgres}}
      POSTGRES_PASSWORD: ${{WW_DB_PASSWORD:-postgres}}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:${{WW_DB_EXTERNAL_PORT:-{db_external_port}}}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${{WW_DB_USER:-postgres}} -d ${{WW_DB_NAME:-worldweaver_{city_id}}}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build:
      context: ../../worldweaver_engine
      dockerfile: Dockerfile
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ../../worldweaver_engine:/app
      - ./data:/app/data
      - ./residents:/app/residents
      - ./identity:/app/identity:ro
    env_file: .env
    environment:
      WW_DB_HOST: ${{WW_DB_HOST:-db}}
      WW_DB_PORT: ${{WW_DB_PORT:-5432}}
      WW_DB_NAME: ${{WW_DB_NAME:-worldweaver_{city_id}}}
      WW_DB_USER: ${{WW_DB_USER:-postgres}}
      WW_DB_PASSWORD: ${{WW_DB_PASSWORD:-postgres}}
      WW_DATABASE_URL: ${{WW_DATABASE_URL:-}}
      WW_AGENT_RESIDENTS_DIR: /app/residents
      WW_PUBLIC_URL: ${{WW_RUNTIME_PUBLIC_URL:-${{WW_PUBLIC_URL}}}}
      WW_CLIENT_URL: ${{WW_CLIENT_URL:-}}
      FEDERATION_URL: ${{WW_RUNTIME_FEDERATION_URL:-${{FEDERATION_URL}}}}
    ports:
      - "${{BACKEND_PORT}}:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      default:
      federation:
        aliases:
          - {shard_id}-backend
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health', timeout=5)"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  agent:
    build:
      context: ../../ww_agent
      dockerfile: Dockerfile
    volumes:
      - ../../ww_agent:/app
      - ./residents:/app/residents
    env_file: .env
    environment:
      WW_SERVER_URL: http://backend:8000
      WW_RESIDENTS_DIR: /app/residents
    depends_on:
      backend:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  federation:
    external: true
    name: ww_dev_federation
"""

_COMPOSE_WORLD = """\
# WorldWeaver federation root: ww_world
# Generated by scripts/new_shard.py
# No agent service — world root runs no simulation loops of its own

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: ${{WW_DB_NAME:-worldweaver_world}}
      POSTGRES_USER: ${{WW_DB_USER:-postgres}}
      POSTGRES_PASSWORD: ${{WW_DB_PASSWORD:-postgres}}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:${{WW_DB_EXTERNAL_PORT:-{db_external_port}}}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${{WW_DB_USER:-postgres}} -d ${{WW_DB_NAME:-worldweaver_world}}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build:
      context: ../../worldweaver_engine
      dockerfile: Dockerfile
    volumes:
      - ../../worldweaver_engine:/app
      - ./data:/app/data
      - ./identity:/app/identity:ro
    env_file: .env
    environment:
      WW_DB_HOST: ${{WW_DB_HOST:-db}}
      WW_DB_PORT: ${{WW_DB_PORT:-5432}}
      WW_DB_NAME: ${{WW_DB_NAME:-worldweaver_world}}
      WW_DB_USER: ${{WW_DB_USER:-postgres}}
      WW_DB_PASSWORD: ${{WW_DB_PASSWORD:-postgres}}
      WW_DATABASE_URL: ${{WW_DATABASE_URL:-}}
    ports:
      - "${BACKEND_PORT}:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      default:
      federation:
        aliases:
          - ww_world-backend
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health', timeout=5)"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

volumes:
  postgres_data:

networks:
  federation:
    name: ww_dev_federation
"""

_GITIGNORE = """\
db/
data/
residents/
.env
*.env
identity/node.key
"""


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def _compose_project_name(shard_id: str) -> str:
    """Return a stable Compose project name owned by this shard folder."""
    normalized = re.sub(r"[^a-z0-9_-]+", "-", shard_id.lower()).strip("-_")
    return normalized or "worldweaver-shard"


def _new_data_encryption_key() -> str:
    """Generate a Fernet-compatible key without importing runtime packages."""
    return base64.urlsafe_b64encode(os.urandom(32)).decode("ascii")


def _city_pack_timezone(city_pack_src: Path | None) -> str:
    if city_pack_src is None:
        return ""
    config_path = city_pack_src / "weather_config.json"
    if not config_path.exists():
        return ""
    try:
        payload = json.loads(config_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return ""
    return str(payload.get("timezone") or "").strip()


def main() -> None:
    parser = argparse.ArgumentParser(description="Create a new WorldWeaver shard directory.")
    parser.add_argument("city_id", help="Shard slug (e.g. portland, tokyo)")
    parser.add_argument("--port", type=int, default=8001, help="Backend port (default: 8001)")
    parser.add_argument("--db-port", type=int, default=None, help="Host-local Postgres port for GUI/psql access (default: derived from backend port)")
    parser.add_argument("--type", dest="shard_type", default="city", choices=["city", "world", "neighborhood"], help="Shard type (default: city)")
    parser.add_argument(
        "--shard-id",
        default="",
        help="Federation-wide node ID (default: generated directory name)",
    )
    parser.add_argument("--federation", default="", help="Federation root URL")
    parser.add_argument(
        "--runtime-federation",
        default="",
        help="Federation URL used inside Docker when it differs from the host-side URL",
    )
    parser.add_argument("--token", default="", help="Shared federation secret (FEDERATION_TOKEN)")
    parser.add_argument("--base-dir", default="..", help="Parent directory (default: ..)")
    parser.add_argument(
        "--city-pack-dir",
        default="",
        help="Path to a pre-built city pack directory (auto-detected from data/cities/<city_id> if omitted)",
    )
    parser.add_argument(
        "--experience",
        default="",
        help="Versioned shard-experience JSON to copy into this node (game shards only)",
    )
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    if args.shard_type == "world" and args.experience:
        parser.error("--experience applies only to city or neighborhood shards")

    city_id = args.city_id.lower().replace(" ", "_").replace("-", "_")

    # Derive shard directory name
    if args.shard_type == "world":
        shard_dir_name = "ww_world"
    else:
        # Map city IDs to IATA airport codes (short, unambiguous, universally understood)
        _short = {
            "san_francisco": "sfo",
            "portland": "pdx",
            "new_york": "jfk",
            "los_angeles": "lax",
            "seattle": "sea",
            "chicago": "ord",
            "miami": "mia",
            "austin": "aus",
            "denver": "den",
            "boston": "bos",
            "tokyo": "nrt",
            "london": "lhr",
            "paris": "cdg",
            "berlin": "ber",
            "nairobi": "nbo",
            "buenos_aires": "eze",
            "alderbank": "alderbank",
        }
        short = _short.get(city_id, city_id[:3])
        shard_dir_name = f"ww_{short}"

    shard_id = str(args.shard_id or shard_dir_name).strip()
    if not shard_id or any(character.isspace() for character in shard_id):
        parser.error("--shard-id must be a non-empty ID without spaces")

    base = Path(args.base_dir).resolve()
    shard_dir = base / shard_dir_name

    if shard_dir.exists():
        print(f"ERROR: {shard_dir} already exists. Remove it first or choose a different name.")
        sys.exit(1)

    # Resolve city pack for non-world shards
    city_pack_src: Path | None = None
    experience_src: Path | None = None
    if args.shard_type != "world":
        if args.city_pack_dir:
            city_pack_src = Path(args.city_pack_dir).resolve()
        else:
            # Auto-detect from <worldweaver_root>/data/cities/<city_id>/
            _script_dir = Path(__file__).resolve().parent
            city_pack_src = _script_dir.parent / "data" / "cities" / city_id

        if not city_pack_src.is_dir():
            print(f"ERROR: City pack not found at {city_pack_src}")
            print()
            print("Build it first with:")
            print(f"  python scripts/build_city_pack.py --city {city_id}")
            print()
            print("Or point to an existing pack with --city-pack-dir PATH")
            sys.exit(1)

        # Verify pack has at minimum a neighborhoods file
        _pack_files = list(city_pack_src.iterdir())
        if not _pack_files:
            print(f"ERROR: City pack directory is empty: {city_pack_src}")
            sys.exit(1)

        if args.experience:
            experience_src = Path(args.experience).resolve()
            if not experience_src.is_file() or experience_src.suffix.lower() != ".json":
                print(f"ERROR: Shard experience must be an existing JSON file: {experience_src}")
                sys.exit(1)
            try:
                experience_payload = json.loads(experience_src.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError) as exc:
                print(f"ERROR: Could not read shard experience {experience_src}: {exc}")
                sys.exit(1)
            if experience_payload.get("schema") != "worldweaver.shard-experience":
                print("ERROR: --experience does not contain a WorldWeaver shard-experience declaration")
                sys.exit(1)

    # Build file contents
    db_external_port = int(args.db_port) if args.db_port is not None else int(args.port) + 7431
    compose_project_name = _compose_project_name(shard_id)
    jwt_secret = secrets.token_urlsafe(48)
    data_encryption_key = _new_data_encryption_key()
    if args.shard_type == "world":
        env_content = _ENV_WORLD.format(
            shard_id=shard_id,
            port=args.port,
            token=args.token,
            db_external_port=db_external_port,
            compose_project_name=compose_project_name,
            jwt_secret=jwt_secret,
            data_encryption_key=data_encryption_key,
        )
        compose_content = _COMPOSE_WORLD.format(db_external_port=db_external_port)
    else:
        env_content = _ENV_CITY.format(
            city_id=city_id,
            shard_id=shard_id,
            port=args.port,
            db_external_port=db_external_port,
            city_timezone=_city_pack_timezone(city_pack_src),
            experience_path=(f"/app/data/rulesets/{experience_src.name}" if experience_src is not None else ""),
            federation_url=args.federation,
            runtime_federation_url=args.runtime_federation,
            token=args.token,
            compose_project_name=compose_project_name,
            jwt_secret=jwt_secret,
            data_encryption_key=data_encryption_key,
        )
        compose_content = _COMPOSE_CITY.format(
            city_id=city_id,
            shard_id=shard_id,
            db_external_port=db_external_port,
        )

    files = {
        shard_dir / ".env": env_content,
        shard_dir / "docker-compose.yml": compose_content,
        shard_dir / ".gitignore": _GITIGNORE,
    }
    dirs = [
        shard_dir / "data",
        shard_dir / "identity",
        shard_dir / "residents",
    ]

    # Print plan
    print(f"\nCreating shard: {shard_dir_name}/")
    print(f"  type      : {args.shard_type}")
    print(f"  shard_id  : {shard_id}")
    if args.shard_type != "world":
        print(f"  city_id   : {city_id}")
    print(f"  port      : {args.port}")
    if args.federation:
        print(f"  federation: {args.federation}")
    if args.runtime_federation:
        print(f"  container federation: {args.runtime_federation}")
    if args.token:
        print(f"  token     : {'*' * len(args.token)}")
    if city_pack_src is not None:
        print(f"  city pack : {city_pack_src}")
    if experience_src is not None:
        print(f"  experience: {experience_src}")
    print()
    for d in dirs:
        print(f"  mkdir  {d.relative_to(base.parent)}/")
    for path in files:
        print(f"  write  {path.relative_to(base.parent)}")
    if city_pack_src is not None:
        dest_pack = shard_dir / "data" / "cities" / city_id
        print(f"  copy   {city_pack_src}  →  {dest_pack.relative_to(base.parent)}/")
    if experience_src is not None:
        dest_experience = shard_dir / "data" / "rulesets" / experience_src.name
        print(f"  copy   {experience_src}  →  {dest_experience.relative_to(base.parent)}")

    if args.dry_run:
        print("\n[dry-run] No files written.")
        return

    # Write
    shard_dir.mkdir(parents=True)
    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)
        (d / ".gitkeep").write_text("")
    for path, content in files.items():
        path.write_text(content, encoding="utf-8")
    (shard_dir / ".env").chmod(0o600)
    generate_node_identity(
        private_key_path=shard_dir / "identity" / "node.key",
        descriptor_path=shard_dir / "node.json",
        node_id=shard_id,
        shard_type=args.shard_type,
        city_id=city_id if args.shard_type != "world" else None,
    )

    # Copy city pack into shard data dir
    if city_pack_src is not None:
        dest_pack = shard_dir / "data" / "cities" / city_id
        print(f"\nCopying city pack → {dest_pack.relative_to(base.parent)}/")
        shutil.copytree(city_pack_src, dest_pack)
    if experience_src is not None:
        dest_experience = shard_dir / "data" / "rulesets" / experience_src.name
        dest_experience.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(experience_src, dest_experience)

    print(f"\nDone. Shard directory created at: {shard_dir}")
    print()
    if args.shard_type == "world":
        print("Next steps:")
        print(f"  docker compose -p ww_world -f {shard_dir}/docker-compose.yml up -d")
        print()
        print("Then register city shards against this world root.")
    else:
        print("Next steps:")
        print(f"  1. Add residents to {shard_dir}/residents/")
        print(f"  2. Start backend:  docker compose -p {shard_dir_name} -f {shard_dir}/docker-compose.yml up -d backend")
        print(f"  3. Seed world:     python scripts/seed_world.py --shard-dir {shard_dir}")
        print(f"  4. Start agents:   docker compose -p {shard_dir_name} -f {shard_dir}/docker-compose.yml up -d agent")


if __name__ == "__main__":
    main()
