"""
new_shard.py — Create a new WorldWeaver shard directory from template.

Usage:
    python scripts/new_shard.py <city_id> [OPTIONS]

    <city_id>           Slug for the new shard (e.g. portland, tokyo, mission)
    --port PORT         Backend port (default: 8001)
    --type TYPE         Shard type: city | world | neighborhood (default: city)
    --federation URL    Federation root URL (e.g. http://localhost:9000)
    --token SECRET      Shared secret for federation auth (FEDERATION_TOKEN)
    --base-dir DIR      Parent directory for the shard (default: ..)
    --city-pack-dir DIR Path to a pre-built city pack directory (auto-detected if omitted)
    --dry-run           Print what would be created without writing files

Examples:
    # Create a Portland city shard (auto-detects data/cities/portland/)
    python scripts/new_shard.py portland --port 8001 \\
        --federation http://host.docker.internal:9000 --token my-secret

    # Create a Portland city shard with explicit city pack path
    python scripts/new_shard.py portland --port 8001 \\
        --city-pack-dir /path/to/portland \\
        --federation http://host.docker.internal:9000 --token my-secret

    # Create the world federation root
    python scripts/new_shard.py world --type world --port 9000 --token my-secret

    # Then seed the shard:
    python scripts/seed_world.py --shard-dir ../ww_pdx
"""
from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------

_ENV_CITY = """\
CITY_ID={city_id}
BACKEND_PORT={port}
SHARD_TYPE=city
FEDERATION_URL={federation_url}
FEDERATION_TOKEN={token}
WW_PUBLIC_URL=http://localhost:{port}
CITY_DB_FILE=worldweaver_{city_id}.db
WW_JWT_SECRET=CHANGE_ME
WW_DATA_ENCRYPTION_KEY=CHANGE_ME
RESEND_API_KEY=
RESEND_FROM_EMAIL=noreply@worldweaver.example.com
OPENROUTER_API_KEY=
LLM_BASE_URL=https://openrouter.ai/api/v1
LLM_MODEL=google/gemini-3-flash-preview
LLM_REFEREE_MODEL=google/gemini-3-flash-preview
LLM_NARRATOR_MODEL=google/gemini-3-flash-preview
WW_INFERENCE_KEY=
WW_INFERENCE_URL=https://openrouter.ai/api/v1
WW_INFERENCE_MODEL=google/gemini-3-flash-preview
WW_DOULA=1
WW_DOULA_MODEL=
"""

_ENV_WORLD = """\
BACKEND_PORT={port}
SHARD_TYPE=world
FEDERATION_TOKEN={token}
CITY_DB_FILE=worldweaver_world.db
WW_PUBLIC_URL=http://localhost:{port}
WW_JWT_SECRET=CHANGE_ME
WW_DATA_ENCRYPTION_KEY=CHANGE_ME
RESEND_API_KEY=
RESEND_FROM_EMAIL=noreply@worldweaver.example.com
OPENROUTER_API_KEY=
LLM_BASE_URL=https://openrouter.ai/api/v1
LLM_MODEL=google/gemini-3-flash-preview
LLM_REFEREE_MODEL=google/gemini-3-flash-preview
LLM_NARRATOR_MODEL=google/gemini-3-flash-preview
"""

_COMPOSE_CITY = """\
# WorldWeaver shard: {city_id}
# Generated by scripts/new_shard.py
# Mounts ../../worldweaver_engine (shared code) and ./residents (shard-local canonical residents)

services:
  backend:
    build:
      context: ../../worldweaver_engine
      dockerfile: Dockerfile
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ../../worldweaver_engine:/app
      - ./db:/app/db
      - ./data:/app/data
      - ./residents:/app/residents
    env_file: .env
    environment:
      WW_DB_PATH: /app/db/${{CITY_DB_FILE}}
      WW_AGENT_RESIDENTS_DIR: /app/residents
    ports:
      - "${{BACKEND_PORT}}:8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health', timeout=5)"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  agent:
    build:
      context: ../../ww_agent
      dockerfile: Dockerfile
    volumes:
      - ../../ww_agent:/app
      - ./residents:/app/residents
    env_file: .env
    environment:
      WW_SERVER_URL: http://backend:8000
      WW_RESIDENTS_DIR: /app/residents
    depends_on:
      backend:
        condition: service_healthy
"""

_COMPOSE_WORLD = """\
# WorldWeaver federation root: ww_world
# Generated by scripts/new_shard.py
# No agent service — world root runs no simulation loops of its own

services:
  backend:
    build:
      context: ../../worldweaver_engine
      dockerfile: Dockerfile
    volumes:
      - ../../worldweaver_engine:/app
      - ./db:/app/db
      - ./data:/app/data
    env_file: .env
    environment:
      WW_DB_PATH: /app/db/${CITY_DB_FILE}
    ports:
      - "${BACKEND_PORT}:8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health', timeout=5)"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
"""

_GITIGNORE = """\
db/
data/
residents/
*.env
"""


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(description="Create a new WorldWeaver shard directory.")
    parser.add_argument("city_id", help="Shard slug (e.g. portland, tokyo)")
    parser.add_argument("--port", type=int, default=8001, help="Backend port (default: 8001)")
    parser.add_argument("--type", dest="shard_type", default="city",
                        choices=["city", "world", "neighborhood"],
                        help="Shard type (default: city)")
    parser.add_argument("--federation", default="", help="Federation root URL")
    parser.add_argument("--token", default="", help="Shared federation secret (FEDERATION_TOKEN)")
    parser.add_argument("--base-dir", default="..", help="Parent directory (default: ..)")
    parser.add_argument(
        "--city-pack-dir",
        default="",
        help="Path to a pre-built city pack directory (auto-detected from data/cities/<city_id> if omitted)",
    )
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    city_id = args.city_id.lower().replace(" ", "_").replace("-", "_")

    # Derive shard directory name
    if args.shard_type == "world":
        shard_dir_name = "ww_world"
    else:
        # Map city IDs to IATA airport codes (short, unambiguous, universally understood)
        _short = {
            "san_francisco": "sfo",
            "portland": "pdx",
            "new_york": "jfk",
            "los_angeles": "lax",
            "seattle": "sea",
            "chicago": "ord",
            "miami": "mia",
            "austin": "aus",
            "denver": "den",
            "boston": "bos",
            "tokyo": "nrt",
            "london": "lhr",
            "paris": "cdg",
            "berlin": "ber",
            "nairobi": "nbo",
            "buenos_aires": "eze",
        }
        short = _short.get(city_id, city_id[:3])
        shard_dir_name = f"ww_{short}"

    base = Path(args.base_dir).resolve()
    shard_dir = base / shard_dir_name

    if shard_dir.exists():
        print(f"ERROR: {shard_dir} already exists. Remove it first or choose a different name.")
        sys.exit(1)

    # Resolve city pack for non-world shards
    city_pack_src: Path | None = None
    if args.shard_type != "world":
        if args.city_pack_dir:
            city_pack_src = Path(args.city_pack_dir).resolve()
        else:
            # Auto-detect from <worldweaver_root>/data/cities/<city_id>/
            _script_dir = Path(__file__).resolve().parent
            city_pack_src = _script_dir.parent / "data" / "cities" / city_id

        if not city_pack_src.is_dir():
            print(f"ERROR: City pack not found at {city_pack_src}")
            print()
            print("Build it first with:")
            print(f"  python scripts/build_city_pack.py {city_id}")
            print()
            print("Or point to an existing pack with --city-pack-dir PATH")
            sys.exit(1)

        # Verify pack has at minimum a neighborhoods file
        _pack_files = list(city_pack_src.iterdir())
        if not _pack_files:
            print(f"ERROR: City pack directory is empty: {city_pack_src}")
            sys.exit(1)

    # Build file contents
    if args.shard_type == "world":
        env_content = _ENV_WORLD.format(port=args.port, token=args.token)
        compose_content = _COMPOSE_WORLD
    else:
        env_content = _ENV_CITY.format(
            city_id=city_id,
            port=args.port,
            federation_url=args.federation,
            token=args.token,
        )
        compose_content = _COMPOSE_CITY.format(city_id=city_id)

    files = {
        shard_dir / ".env": env_content,
        shard_dir / "docker-compose.yml": compose_content,
        shard_dir / ".gitignore": _GITIGNORE,
    }
    dirs = [
        shard_dir / "db",
        shard_dir / "data",
        shard_dir / "residents",
    ]

    # Print plan
    print(f"\nCreating shard: {shard_dir_name}/")
    print(f"  type      : {args.shard_type}")
    if args.shard_type != "world":
        print(f"  city_id   : {city_id}")
    print(f"  port      : {args.port}")
    if args.federation:
        print(f"  federation: {args.federation}")
    if args.token:
        print(f"  token     : {'*' * len(args.token)}")
    if city_pack_src is not None:
        print(f"  city pack : {city_pack_src}")
    print()
    for d in dirs:
        print(f"  mkdir  {d.relative_to(base.parent)}/")
    for path in files:
        print(f"  write  {path.relative_to(base.parent)}")
    if city_pack_src is not None:
        dest_pack = shard_dir / "data" / "cities" / city_id
        print(f"  copy   {city_pack_src}  →  {dest_pack.relative_to(base.parent)}/")

    if args.dry_run:
        print("\n[dry-run] No files written.")
        return

    # Write
    shard_dir.mkdir(parents=True)
    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)
        (d / ".gitkeep").write_text("")
    for path, content in files.items():
        path.write_text(content, encoding="utf-8")

    # Copy city pack into shard data dir
    if city_pack_src is not None:
        dest_pack = shard_dir / "data" / "cities" / city_id
        print(f"\nCopying city pack → {dest_pack.relative_to(base.parent)}/")
        shutil.copytree(city_pack_src, dest_pack)

    print(f"\nDone. Shard directory created at: {shard_dir}")
    print()
    if args.shard_type == "world":
        print("Next steps:")
        print(f"  docker compose -p ww_world -f {shard_dir}/docker-compose.yml up -d")
        print()
        print("Then register city shards against this world root.")
    else:
        print("Next steps:")
        print(f"  1. Add residents to {shard_dir}/residents/")
        print(f"  2. Start backend:  docker compose -p {shard_dir_name} -f {shard_dir}/docker-compose.yml up -d backend")
        print(f"  3. Seed world:     python scripts/seed_world.py --shard-dir {shard_dir}")
        print(f"  4. Start agents:   docker compose -p {shard_dir_name} -f {shard_dir}/docker-compose.yml up -d agent")


if __name__ == "__main__":
    main()
